# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aff8d139d9e561ce57bc819be7ed1578e3dfb1bd0600b4e5407d7ba93d1a5fad80dc29ce4df35972f196945dbec70a29e3afbae6852150cdbb09cce141ce2880

test:
  secret_key_base: 363cf5667d3df40397790f4a5fc6806b8a901cdfd447b509d42612b4708e47dc760ca4add71be5c6fdfcf70ff27696247790fd332562afad7f254526bd6a4a83

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
